version: '3'

networks:
  local-sam:
    external: true

services:
  lambdas:
    image: apssouza/aws-sam
    container_name: local-sam
    hostname: local-sam
    environment:
      - DOCKER_VOLUME_BASEDIR=${DOCKER_VOLUME_BASEDIR}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cdk.out/:/sam
    entrypoint: sam local start-api -t /sam/CdkTsStack.template.json  --host 0.0.0.0 --port 3000 --docker-volume-basedir $DOCKER_VOLUME_BASEDIR --container-host host.docker.internal --docker-network local-sam
    ports:
      - '3001:3001'
      - '3000:3000'
    networks:
      - local-sam
  mb:
    image: bbyars/mountebank:2.8.1
    hostname: mb
    container_name: mock-server
    volumes:
      - ./testing/integration/mockfiles/:/templates/
    entrypoint: mb start --configfile /templates/imposters.json --allowInjection
    networks:
      - local-sam
    ports:
      - '2525:2525'
      - '4545:4545'
      - '5555:5555'
#
  integration-test:
    image: curlimages/curl:7.73.0
    depends_on:
      - lambdas
      - mb
    networks:
      - local-sam
    volumes:
      - .:/app
    entrypoint: "curl -L 'http://lambdas:3000/lambada2'"

  dockerize:
    image: dockerize:0.6.0